#!/bin/bash

#
# This is a quick and dirty script to build the test class, and run it.
# It must be run from the physion/trunk directory.
#

export CLASSPATH="src:lib/datetimepicker3.3.jar"
echo CLASSPATH=${CLASSPATH}

# Build the source tree.
echo pwd=`pwd`
javac src/com/physion/ovation/gui/ebuilder/*.java

# Run the test program.
#java com.physion.ovation.gui.ebuilder.TestEBuilder
java com.physion.ovation.gui.ebuilder.ExpressionBuilder
