#!/bin/bash

#
# This is a quick and dirty script to build the GUI, and run it.
# It must be run from the physion/trunk directory.
#

export CLASSPATH="src:lib/datetimepicker3.3.jar:lib/junit-4.10.jar:lib/ApprovalTests.jar"
echo CLASSPATH=${CLASSPATH}

# Build the source tree.
echo pwd=`pwd`
javac src/com/physion/ovation/gui/ebuilder/*.java

# Run the test program.
java com.physion.ebuilder.ExpressionBuilder
