#!/bin/bash

#
# This script checks out or updates the source tree in the directory
# specified on the command line.
#

if [ -z $1 ]
then
    echo You must specify the name of the directory you want me to create
    echo "or update.  The source tree 'trunk' directory will be checked out"
    echo under this directory.
    echo You can optionally specify a Subversion Revision echo number also.
    echo For example, to create directory test123/trunk and use Revision 2385:
    echo "    checkout test123 2385"
    exit
fi

# Make the directory if it does not already exist.
if [ ! -d $1 ]
then
   mkdir -p $1
fi
cd $1
echo "Source tree 'trunk' directory will be under the directory '`pwd`'."

if [ -z $2 ]
then
echo "No revision number specified.  I will check out latest revision."
echo "It will take me a few seconds to retrieve the latest revision number..."
echo Latest revision is `svn info https://svn.physionconsulting.com/ovpredicateui/trunk |grep Revision`
else
echo Will check out Revision: $2
REVISION_NUM='-r '$2
fi

echo
echo =====================================================================
echo "=                   Checking Out Source Files                       ="
echo =====================================================================
echo

echo svn co ${REVISION_NUM} https://svn.physionconsulting.com/ovpredicateui/trunk
svn co ${REVISION_NUM} https://svn.physionconsulting.com/ovpredicateui/trunk

